import {
  BadRequestException,
  Injectable,
  InternalServerErrorException,
  NotFoundException,
} from '@nestjs/common';
import { PrismaService } from './prisma.service';

type ProjectionRow = {
  rowId: string;
  transactionId: number;
  date: string;
  info: string;
  type: string;
  isCleared: boolean;
  isSalaryIncome: boolean;
  accountId: number | null;
  accountName: string;
  income: number;
  expense: number;
  accountBalanceAfter: number | null;
  totalBalanceAfter: number;
  isRecurringGenerated: boolean;
  isAutoGenerated: boolean;
  generationKind: string | null;
  transactionGroupId: number | null;
  transactionGroupName: string | null;
  transactionSubgroupId: number | null;
  transactionSubgroupName: string | null;
  recurringTemplateId: number | null;
  transferSide: 'out' | 'in' | null;
};

type TransactionWithCategory = {
  id: number;
  date: Date;
  info: string;
  type: string;
  isCleared: boolean;
  isSalaryIncome: boolean;
  income: unknown | null;
  expense: unknown | null;
  accountId: number | null;
  sourceAccountId: number | null;
  destinationAccountId: number | null;
  recurringTemplateId: number | null;
  isGenerated: boolean;
  generationKind: string | null;
  autoGeneratedSourceAccountId: number | null;
  transactionGroupId: number | null;
  transactionSubgroupId: number | null;
  transactionGroup?: {
    id: number;
    name: string;
  } | null;
  transactionSubgroup?: {
    id: number;
    name: string;
  } | null;
};

@Injectable()
export class ProjectionService {
  constructor(private prisma: PrismaService) {}

  async getAllAccounts() {
    const accounts = await this.prisma.account.findMany({
      select: {
        id: true,
        name: true,
        accountTypeId: true,
        accountType: {
          select: {
            id: true,
            code: true,
            name: true,
          },
        },
        initialBalance: true,
        includeInDailyBudget: true,
        creditLimit: true,
        repaymentAccountId: true,
        autoRepaymentEnabled: true,
        autoRepaymentOffsetDays: true,
        autoRepaymentGroupId: true,
        autoRepaymentSubgroupId: true,
        autoRepaymentGroup: { select: { id: true, name: true } },
        autoRepaymentSubgroup: { select: { id: true, name: true } },
        repaymentAccount: {
          select: {
            id: true,
            name: true,
          },
        },
      },
      orderBy: { id: 'asc' },
    });

    return accounts.map((account) => ({
      ...account,
      initialBalance: Number(account.initialBalance),
      creditLimit: account.creditLimit != null ? Number(account.creditLimit) : null,
    }));
  }

  async getTransactionGroups() {
    return this.prisma.transactionGroup.findMany({
      where: { isActive: true },
      include: {
        subgroups: {
          where: { isActive: true },
          orderBy: { sortOrder: 'asc' },
        },
      },
      orderBy: { sortOrder: 'asc' },
    });
  }

  async getTransactionGroupsAdmin(includeInactive = true) {
    return this.prisma.transactionGroup.findMany({
      where: includeInactive ? undefined : { isActive: true },
      include: {
        subgroups: {
          where: includeInactive ? undefined : { isActive: true },
          orderBy: [{ sortOrder: 'asc' }, { id: 'asc' }],
        },
      },
      orderBy: [{ sortOrder: 'asc' }, { id: 'asc' }],
    });
  }

  private normalizeCategoryCode(value: string) {
    return value
      .trim()
      .toLowerCase()
      .replace(/\s+/g, '-')
      .replace(/[^a-z0-9-_]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '');
  }

  private normalizeCategoryName(value: string) {
    return value?.trim();
  }

  private parseSortOrder(value: number | string | undefined) {
    if (value === undefined || value === null || value === '') {
      return 0;
    }

    const parsed = Number(value);

    if (!Number.isFinite(parsed)) {
      throw new BadRequestException('Pole sortOrder musi być liczbą.');
    }

    return parsed;
  }

  private async ensureTransactionGroupExists(groupId: number) {
    const group = await this.prisma.transactionGroup.findFirst({
      where: { id: groupId },
    });

    if (!group) {
      throw new NotFoundException('Grupa transakcji nie istnieje.');
    }

    return group;
  }

  private async ensureTransactionSubgroupExists(subgroupId: number) {
    const subgroup = await this.prisma.transactionSubgroup.findFirst({
      where: { id: subgroupId },
    });

    if (!subgroup) {
      throw new NotFoundException('Podgrupa transakcji nie istnieje.');
    }

    return subgroup;
  }

  private async ensureAccountExists(accountId: number) {
    const account = await this.prisma.account.findFirst({ where: { id: accountId } });
    if (!account) {
      throw new NotFoundException('Konto nie istnieje lub nie należy do bieżącego użytkownika.');
    }
    return account;
  }

  private assertCategoryEditable(isSystem: boolean, entityLabel: string) {
    if (isSystem) {
      throw new BadRequestException(`${entityLabel} systemowa nie może być modyfikowana z poziomu aplikacji.`);
    }
  }
  
  async createTransactionGroup(data: {
    code: string;
    name: string;
    sortOrder?: number;
  }) {
    const name = this.normalizeCategoryName(data.name);
    const code = this.normalizeCategoryCode(data.code);

    if (!name) {
      throw new BadRequestException('Nazwa grupy jest wymagana.');
    }

    if (!code) {
      throw new BadRequestException('Kod grupy jest wymagany.');
    }

    const existing = await this.prisma.transactionGroup.findFirst({
      where: { code },
    });

    if (existing) {
      throw new BadRequestException('Grupa o takim kodzie już istnieje.');
    }

    return this.prisma.transactionGroup.create({
      data: {
        userId: 0,
        code,
        name,
        sortOrder: this.parseSortOrder(data.sortOrder),
        isSystem: false,
        isActive: true,
      },
    });
  }

  async updateTransactionGroup(
    id: number,
    data: {
      code: string;
      name: string;
      sortOrder?: number;
    },
  ) {
    const existing = await this.ensureTransactionGroupExists(id);
    this.assertCategoryEditable(existing.isSystem, 'Grupa');

    const name = this.normalizeCategoryName(data.name);
    const code = this.normalizeCategoryCode(data.code);

    if (!name) {
      throw new BadRequestException('Nazwa grupy jest wymagana.');
    }

    if (!code) {
      throw new BadRequestException('Kod grupy jest wymagany.');
    }

    const duplicate = await this.prisma.transactionGroup.findFirst({
      where: { code },
    });

    if (duplicate && duplicate.id !== id) {
      throw new BadRequestException('Grupa o takim kodzie już istnieje.');
    }

    return this.prisma.transactionGroup.update({
      where: { id },
      data: {
        code,
        name,
        sortOrder: this.parseSortOrder(data.sortOrder),
      },
    });
  }

  async deactivateTransactionGroup(id: number) {
    const existing = await this.ensureTransactionGroupExists(id);
    this.assertCategoryEditable(existing.isSystem, 'Grupa');

    await this.prisma.$transaction([
      this.prisma.transactionSubgroup.updateMany({
        where: { transactionGroupId: id },
        data: { isActive: false },
      }),
      this.prisma.transactionGroup.update({
        where: { id },
        data: { isActive: false },
      }),
    ]);

    return { success: true };
  }

  async createTransactionSubgroup(data: {
    transactionGroupId: number;
    code: string;
    name: string;
    sortOrder?: number;
  }) {
    const transactionGroupId = Number(data.transactionGroupId);
    const name = this.normalizeCategoryName(data.name);
    const code = this.normalizeCategoryCode(data.code);

    if (!transactionGroupId) {
      throw new BadRequestException('Grupa nadrzędna jest wymagana.');
    }

    if (!name) {
      throw new BadRequestException('Nazwa podgrupy jest wymagana.');
    }

    if (!code) {
      throw new BadRequestException('Kod podgrupy jest wymagany.');
    }

    const group = await this.ensureTransactionGroupExists(transactionGroupId);

    if (!group.isActive) {
      throw new BadRequestException('Nie można dodać podgrupy do nieaktywnej grupy.');
    }

    const existing = await this.prisma.transactionSubgroup.findFirst({
      where: { code },
    });

    if (existing) {
      throw new BadRequestException('Podgrupa o takim kodzie już istnieje.');
    }

    return this.prisma.transactionSubgroup.create({
      data: {
        userId: 0,
        transactionGroupId,
        code,
        name,
        sortOrder: this.parseSortOrder(data.sortOrder),
        isSystem: false,
        isActive: true,
      },
    });
  }

  async updateTransactionSubgroup(
    id: number,
    data: {
      transactionGroupId: number;
      code: string;
      name: string;
      sortOrder?: number;
    },
  ) {
    const existing = await this.ensureTransactionSubgroupExists(id);
    this.assertCategoryEditable(existing.isSystem, 'Podgrupa');

    const transactionGroupId = Number(data.transactionGroupId);
    const name = this.normalizeCategoryName(data.name);
    const code = this.normalizeCategoryCode(data.code);

    if (!transactionGroupId) {
      throw new BadRequestException('Grupa nadrzędna jest wymagana.');
    }

    if (!name) {
      throw new BadRequestException('Nazwa podgrupy jest wymagana.');
    }

    if (!code) {
      throw new BadRequestException('Kod podgrupy jest wymagany.');
    }

    const group = await this.ensureTransactionGroupExists(transactionGroupId);

    if (!group.isActive) {
      throw new BadRequestException('Nie można przypisać podgrupy do nieaktywnej grupy.');
    }

    const duplicate = await this.prisma.transactionSubgroup.findFirst({
      where: { code },
    });

    if (duplicate && duplicate.id !== id) {
      throw new BadRequestException('Podgrupa o takim kodzie już istnieje.');
    }

    return this.prisma.transactionSubgroup.update({
      where: { id },
      data: {
        transactionGroupId,
        code,
        name,
        sortOrder: this.parseSortOrder(data.sortOrder),
      },
    });
  }

  async deactivateTransactionSubgroup(id: number) {
    const existing = await this.ensureTransactionSubgroupExists(id);
    this.assertCategoryEditable(existing.isSystem, 'Podgrupa');

    await this.prisma.transactionSubgroup.update({
      where: { id },
      data: { isActive: false },
    });

    return { success: true };
  }

  async createAccount(data: {
    name: string;
    accountTypeId: number;
    initialBalance?: number;
    includeInDailyBudget?: boolean;
    creditLimit?: number;
    repaymentAccountId?: number | null;
    autoRepaymentEnabled?: boolean;
    autoRepaymentOffsetDays?: number;
    autoRepaymentGroupId?: number | null;
    autoRepaymentSubgroupId?: number | null;
  }) {
    const name = data.name?.trim();
    if (!name) {
      throw new BadRequestException('Nazwa konta jest wymagana.');
    }

    const accountTypeId = Number(data.accountTypeId);
    const creditLimit =
      data.creditLimit != null && Number(data.creditLimit) !== 0
        ? Number(data.creditLimit)
        : null;

    const repaymentAccountId =
      data.repaymentAccountId != null ? Number(data.repaymentAccountId) : null;

    const autoRepaymentEnabled = Boolean(data.autoRepaymentEnabled ?? false);
    const autoRepaymentOffsetDays = Number(data.autoRepaymentOffsetDays ?? 1);
    const autoRepaymentGroupId =
      data.autoRepaymentGroupId != null ? Number(data.autoRepaymentGroupId) : null;
    const autoRepaymentSubgroupId =
      data.autoRepaymentSubgroupId != null ? Number(data.autoRepaymentSubgroupId) : null;

    const accountType = await this.prisma.accountType.findUnique({
      where: { id: accountTypeId },
    });

    if (!accountType) {
      throw new BadRequestException('Wybrany typ konta nie istnieje.');
    }

    const isCreditCard =
      accountType.code === 'credit_card' || accountType.code === 'credit_card';

    if (!isCreditCard && creditLimit != null) {
      throw new BadRequestException('Limit kredytowy można ustawić tylko dla karty kredytowej.');
    }

    if (!isCreditCard && repaymentAccountId != null) {
      throw new BadRequestException('Konto spłaty można ustawić tylko dla karty kredytowej.');
    }

    if (!isCreditCard && autoRepaymentEnabled) {
      throw new BadRequestException('Automatyczna spłata jest dostępna tylko dla kart kredytowych.');
    }

    if (!isCreditCard && (autoRepaymentGroupId != null || autoRepaymentSubgroupId != null)) {
      throw new BadRequestException('Kategorię spłaty można ustawić tylko dla karty kredytowej.');
    }

    if (!isCreditCard && autoRepaymentOffsetDays !== 1) {
      throw new BadRequestException('Offset spłaty można ustawić tylko dla kart kredytowych.');
    }

    if (autoRepaymentOffsetDays < 0 || autoRepaymentOffsetDays > 31) {
      throw new BadRequestException('Offset spłaty musi mieścić się w zakresie 0-31 dni.');
    }

    if (autoRepaymentEnabled && repaymentAccountId == null) {
      throw new BadRequestException('Automatyczna spłata wymaga wskazania konta spłaty.');
    }

    await this.validateTransactionCategory(autoRepaymentGroupId, autoRepaymentSubgroupId);

    if (repaymentAccountId != null) {
      const repaymentAccount = await this.prisma.account.findUnique({
        where: { id: repaymentAccountId },
      });

      if (!repaymentAccount) {
        throw new BadRequestException('Wybrane konto spłaty nie istnieje.');
      }
    }

    return this.prisma.account.create({
      data: {
        userId: 0,
        name,
        accountTypeId,
        initialBalance: Number(data.initialBalance ?? 0),
        includeInDailyBudget: data.includeInDailyBudget ?? true,
        creditLimit,
        repaymentAccountId,
        autoRepaymentEnabled: isCreditCard ? autoRepaymentEnabled : false,
        autoRepaymentOffsetDays: isCreditCard ? autoRepaymentOffsetDays : 1,
        autoRepaymentGroupId: isCreditCard ? autoRepaymentGroupId : null,
        autoRepaymentSubgroupId: isCreditCard ? autoRepaymentSubgroupId : null,
      },
    });
  }



  async updateAccount(
    id: number,
    data: {
      name: string;
      accountTypeId?: number;
      initialBalance?: number;
      includeInDailyBudget?: boolean;
      creditLimit?: number | null;
      repaymentAccountId?: number | null;
      autoRepaymentEnabled?: boolean;
      autoRepaymentOffsetDays?: number;
      autoRepaymentGroupId?: number | null;
      autoRepaymentSubgroupId?: number | null;
    },
  ) {
    const existing = await this.prisma.account.findUnique({ where: { id } });

    if (!existing) {
      throw new NotFoundException(`Konto ${id} nie istnieje.`);
    }

    const name = data.name?.trim();
    if (!name) {
      throw new BadRequestException('Nazwa konta jest wymagana.');
    }

    const nextAccountTypeId = data.accountTypeId ?? existing.accountTypeId;

    const nextCreditLimit =
      data.creditLimit !== undefined
        ? data.creditLimit === null || Number(data.creditLimit) === 0
          ? null
          : Number(data.creditLimit)
        : existing.creditLimit != null
          ? Number(existing.creditLimit)
          : null;

    const nextRepaymentAccountId =
      data.repaymentAccountId !== undefined
        ? data.repaymentAccountId === null
          ? null
          : Number(data.repaymentAccountId)
        : existing.repaymentAccountId;

    const nextAutoRepaymentEnabled =
      data.autoRepaymentEnabled !== undefined
        ? Boolean(data.autoRepaymentEnabled)
        : existing.autoRepaymentEnabled;

    const nextAutoRepaymentOffsetDays =
      data.autoRepaymentOffsetDays !== undefined
        ? Number(data.autoRepaymentOffsetDays)
        : existing.autoRepaymentOffsetDays;

    const nextAutoRepaymentGroupId =
      data.autoRepaymentGroupId !== undefined
        ? data.autoRepaymentGroupId == null
          ? null
          : Number(data.autoRepaymentGroupId)
        : existing.autoRepaymentGroupId;

    const nextAutoRepaymentSubgroupId =
      data.autoRepaymentSubgroupId !== undefined
        ? data.autoRepaymentSubgroupId == null
          ? null
          : Number(data.autoRepaymentSubgroupId)
        : existing.autoRepaymentSubgroupId;

    if (nextRepaymentAccountId === id) {
      throw new BadRequestException('Konto spłaty nie może wskazywać na samo siebie.');
    }

    const accountType = await this.prisma.accountType.findUnique({
      where: { id: nextAccountTypeId },
    });

    if (!accountType) {
      throw new BadRequestException('Wybrany typ konta nie istnieje.');
    }

    const isCreditCard =
      accountType.code === 'credit_card' || accountType.code === 'credit_card';

    if (!isCreditCard && nextCreditLimit != null) {
      throw new BadRequestException('Limit kredytowy można ustawić tylko dla karty kredytowej.');
    }

    if (!isCreditCard && nextRepaymentAccountId != null) {
      throw new BadRequestException('Konto spłaty można ustawić tylko dla karty kredytowej.');
    }

    if (!isCreditCard && nextAutoRepaymentEnabled) {
      throw new BadRequestException('Automatyczna spłata jest dostępna tylko dla kart kredytowych.');
    }

    if (!isCreditCard && (nextAutoRepaymentGroupId != null || nextAutoRepaymentSubgroupId != null)) {
      throw new BadRequestException('Kategorię spłaty można ustawić tylko dla karty kredytowej.');
    }

    if (!isCreditCard && nextAutoRepaymentOffsetDays !== 1) {
      throw new BadRequestException('Offset spłaty można ustawić tylko dla kart kredytowych.');
    }

    if (nextAutoRepaymentOffsetDays < 0 || nextAutoRepaymentOffsetDays > 31) {
      throw new BadRequestException('Offset spłaty musi mieścić się w zakresie 0-31 dni.');
    }

    if (nextAutoRepaymentEnabled && nextRepaymentAccountId == null) {
      throw new BadRequestException('Automatyczna spłata wymaga wskazania konta spłaty.');
    }

    await this.validateTransactionCategory(
      isCreditCard ? nextAutoRepaymentGroupId : null,
      isCreditCard ? nextAutoRepaymentSubgroupId : null,
    );

    if (nextRepaymentAccountId != null) {
      const repaymentAccount = await this.prisma.account.findUnique({
        where: { id: nextRepaymentAccountId },
      });

      if (!repaymentAccount) {
        throw new BadRequestException('Wybrane konto spłaty nie istnieje.');
      }
    }

    return this.prisma.account.update({
      where: { id },
      data: {
        name,
        accountTypeId: nextAccountTypeId,
        initialBalance: Number(data.initialBalance ?? existing.initialBalance),
        includeInDailyBudget: data.includeInDailyBudget ?? existing.includeInDailyBudget,
        creditLimit: nextCreditLimit,
        repaymentAccountId: nextRepaymentAccountId,
        autoRepaymentEnabled: isCreditCard ? nextAutoRepaymentEnabled : false,
        autoRepaymentOffsetDays: isCreditCard ? nextAutoRepaymentOffsetDays : 1,
        autoRepaymentGroupId: isCreditCard ? nextAutoRepaymentGroupId : null,
        autoRepaymentSubgroupId: isCreditCard ? nextAutoRepaymentSubgroupId : null,
      },
    });
  }

  async deleteAccount(id: number) {
    const existing = await this.prisma.account.findUnique({
      where: { id },
      include: {
        transactions: { select: { id: true } },
        templates: { select: { id: true } },
        sourceTransfers: { select: { id: true } },
        destTransfers: { select: { id: true } },
        creditCardsToRepay: { select: { id: true } },
        autoGeneratedTransactions: { select: { id: true } },
      },
    });

    if (!existing) throw new NotFoundException(`Konto ${id} nie istnieje.`);

    const hasRelations =
      existing.transactions.length > 0 ||
      existing.templates.length > 0 ||
      existing.sourceTransfers.length > 0 ||
      existing.destTransfers.length > 0 ||
      existing.creditCardsToRepay.length > 0 ||
      existing.autoGeneratedTransactions.length > 0;

    if (hasRelations) {
      throw new BadRequestException(
        'Nie można usunąć konta, które ma powiązane transakcje, przelewy lub szablony.',
      );
    }

    await this.prisma.account.delete({ where: { id } });
  }

  private async validateTransactionCategory(
    transactionGroupId: number | null,
    transactionSubgroupId: number | null,
  ) {
    if (transactionSubgroupId != null && transactionGroupId == null) {
      throw new BadRequestException('Podgrupa wymaga wskazania grupy.');
    }

    if (transactionGroupId != null) {
      const group = await this.prisma.transactionGroup.findFirst({
        where: { id: transactionGroupId },
      });

      if (!group || !group.isActive) {
        throw new BadRequestException('Wybrana grupa transakcji nie istnieje.');
      }
    }

    if (transactionSubgroupId != null) {
      const subgroup = await this.prisma.transactionSubgroup.findFirst({
        where: { id: transactionSubgroupId },
      });

      if (!subgroup || !subgroup.isActive) {
        throw new BadRequestException('Wybrana podgrupa transakcji nie istnieje.');
      }

      if (subgroup.transactionGroupId !== transactionGroupId) {
        throw new BadRequestException('Podgrupa nie należy do wybranej grupy.');
      }
    }
  }


  async createTransaction(data: {
    date: string;
    accountId?: number;
    sourceAccountId?: number;
    destinationAccountId?: number;
    info: string;
    income?: number;
    expense?: number;
    type?: string;
    isSalaryIncome?: boolean;
    transactionGroupId?: number | null;
    transactionSubgroupId?: number | null;
  }) {
    const type = data.type ?? 'transaction';
    const income = data.income ? Number(data.income) : 0;
    const expense = data.expense ? Number(data.expense) : 0;

    if (!data.info?.trim()) {
      throw new BadRequestException('Opis transakcji jest wymagany.');
    }

    if (!data.date) {
      throw new BadRequestException('Data transakcji jest wymagana.');
    }

    if (type === 'transfer') {
      if (!data.sourceAccountId || !data.destinationAccountId) {
        throw new BadRequestException('Transfer wymaga konta źródłowego i docelowego.');
      }

      if (data.sourceAccountId === data.destinationAccountId) {
        throw new BadRequestException('Konta transferu muszą być różne.');
      }

      if (expense <= 0) {
        throw new BadRequestException('Transfer wymaga dodatniej kwoty.');
      }
    } else {
      if (!data.accountId) {
        throw new BadRequestException('Zwykła transakcja wymaga konta.');
      }

      if (income <= 0 && expense <= 0) {
        throw new BadRequestException('Podaj wpłatę lub wypłatę.');
      }
    }

    await this.validateTransactionCategory(
      data.transactionGroupId ?? null,
      data.transactionSubgroupId ?? null,
    );
    if (type === 'transfer') {
      await Promise.all([
        this.ensureAccountExists(Number(data.sourceAccountId)),
        this.ensureAccountExists(Number(data.destinationAccountId)),
      ]);
    } else {
      await this.ensureAccountExists(Number(data.accountId));
    }

return this.prisma.transaction.create({
      data: {
        userId: 0,
        date: this.normalizeDate(data.date),
        info: data.info.trim(),
        type,
        income: income > 0 ? income : null,
        expense: expense > 0 ? expense : null,
        accountId: type === 'transfer' ? null : (data.accountId ?? null),
        sourceAccountId: type === 'transfer' ? (data.sourceAccountId ?? null) : null,
        destinationAccountId: type === 'transfer' ? (data.destinationAccountId ?? null) : null,
        isSalaryIncome: type === 'transfer' ? false : (data.isSalaryIncome ?? false),
        transactionGroupId: data.transactionGroupId ?? null,
        transactionSubgroupId: data.transactionSubgroupId ?? null,
        isCleared: false,
        isGenerated: false,
        generationKey: null,
        generationKind: null,
        autoGeneratedSourceAccountId: null,
        recurringTemplateId: null,
        recurrenceDate: null,
      },
    });
  }

  async updateTransaction(
    id: number,
    data: {
      date: string;
      accountId?: number;
      sourceAccountId?: number;
      destinationAccountId?: number;
      info: string;
      income?: number;
      expense?: number;
      type?: string;
      isSalaryIncome?: boolean;
      transactionGroupId?: number | null;
      transactionSubgroupId?: number | null;
    },
  ) {
    const existing = await this.prisma.transaction.findUnique({ where: { id } });

    if (!existing) {
      throw new NotFoundException(`Transakcja ${id} nie istnieje.`);
    }

    const type = data.type ?? 'transaction';
    const income = data.income ? Number(data.income) : 0;
    const expense = data.expense ? Number(data.expense) : 0;

    if (!data.info?.trim()) {
      throw new BadRequestException('Opis transakcji jest wymagany.');
    }

    if (!data.date) {
      throw new BadRequestException('Data transakcji jest wymagana.');
    }

    if (type === 'transfer') {
      if (!data.sourceAccountId || !data.destinationAccountId) {
        throw new BadRequestException('Transfer wymaga konta źródłowego i docelowego.');
      }

      if (data.sourceAccountId === data.destinationAccountId) {
        throw new BadRequestException('Konta transferu muszą być różne.');
      }

      if (expense <= 0) {
        throw new BadRequestException('Transfer wymaga dodatniej kwoty.');
      }
    } else {
      if (!data.accountId) {
        throw new BadRequestException('Zwykła transakcja wymaga konta.');
      }

      if (income <= 0 && expense <= 0) {
        throw new BadRequestException('Podaj wpłatę lub wypłatę.');
      }
    }

    await this.validateTransactionCategory(
      data.transactionGroupId ?? null,
      data.transactionSubgroupId ?? null,
    );
    if (type === 'transfer') {
      await Promise.all([
        this.ensureAccountExists(Number(data.sourceAccountId)),
        this.ensureAccountExists(Number(data.destinationAccountId)),
      ]);
    } else {
      await this.ensureAccountExists(Number(data.accountId));
    }

    const transactionUpdate = this.prisma.transaction.update({
      where: { id },
      data: {
        date: this.normalizeDate(data.date),
        info: data.info.trim(),
        type,
        income: income > 0 ? income : null,
        expense: expense > 0 ? expense : null,
        accountId: type === 'transfer' ? null : (data.accountId ?? null),
        sourceAccountId: type === 'transfer' ? (data.sourceAccountId ?? null) : null,
        destinationAccountId: type === 'transfer' ? (data.destinationAccountId ?? null) : null,
        isSalaryIncome: type === 'transfer' ? false : (data.isSalaryIncome ?? false),
        transactionGroupId: data.transactionGroupId ?? null,
        transactionSubgroupId: data.transactionSubgroupId ?? null,
      },
    });

    // Kategoria automatycznej spłaty jest ustawieniem karty. Bez tej
    // synchronizacji generator projekcji przywracał poprzednią kategorię
    // natychmiast po ręcznej edycji wygenerowanego przelewu.
    if (existing.generationKind === 'auto_repayment' && existing.autoGeneratedSourceAccountId) {
      const [updated] = await this.prisma.$transaction([
        transactionUpdate,
        this.prisma.account.update({
          where: { id: existing.autoGeneratedSourceAccountId },
          data: {
            autoRepaymentGroupId: data.transactionGroupId ?? null,
            autoRepaymentSubgroupId: data.transactionSubgroupId ?? null,
          },
        }),
      ]);
      return updated;
    }

    return transactionUpdate;
  }

  async deleteTransaction(id: number) {
    const existing = await this.prisma.transaction.findUnique({ where: { id } });
    if (!existing) {
      throw new NotFoundException(`Transakcja ${id} nie istnieje.`);
    }

    await this.prisma.transaction.delete({ where: { id } });
  }

  async createRecurringTemplate(data: {
    accountId: number;
    info: string;
    amount: number;
    startDate: string;
    endDate?: string;
    multiplier?: number;
    period: string;
    dayOfMonth?: number;
    transactionGroupId?: number | null;
    transactionSubgroupId?: number | null;
  }) {
    this.validateRecurringTemplateInput(data);
    await this.validateTransactionCategory(
      data.transactionGroupId ?? null,
      data.transactionSubgroupId ?? null,
    );
    await this.ensureAccountExists(Number(data.accountId));

    return this.prisma.recurringTemplate.create({
      data: {
        userId: 0,
        accountId: Number(data.accountId),
        info: data.info.trim(),
        amount: Number(data.amount),
        startDate: this.normalizeDate(data.startDate),
        endDate: data.endDate ? this.normalizeDate(data.endDate) : null,
        multiplier: data.multiplier ? Number(data.multiplier) : 1,
        period: data.period,
        dayOfMonth: data.dayOfMonth != null ? Number(data.dayOfMonth) : null,
        transactionGroupId: data.transactionGroupId ?? null,
        transactionSubgroupId: data.transactionSubgroupId ?? null,
        isActive: true,
      },
    });
  }

  async updateRecurringTemplate(
    id: number,
    data: {
      accountId: number;
      info: string;
      amount: number;
      startDate: string;
      endDate?: string;
      multiplier?: number;
      period: string;
      dayOfMonth?: number;
      isActive?: boolean;
      transactionGroupId?: number | null;
      transactionSubgroupId?: number | null;
    },
  ) {
    const existing = await this.prisma.recurringTemplate.findUnique({
      where: { id },
    });
    if (!existing) {
      throw new NotFoundException(`Szablon ${id} nie istnieje.`);
    }

    this.validateRecurringTemplateInput(data);
    await this.validateTransactionCategory(
      data.transactionGroupId ?? null,
      data.transactionSubgroupId ?? null,
    );
    await this.ensureAccountExists(Number(data.accountId));

    const updated = await this.prisma.recurringTemplate.update({
      where: { id },
      data: {
        accountId: Number(data.accountId),
        info: data.info.trim(),
        amount: Number(data.amount),
        startDate: this.normalizeDate(data.startDate),
        endDate: data.endDate ? this.normalizeDate(data.endDate) : null,
        multiplier: data.multiplier ? Number(data.multiplier) : 1,
        period: data.period,
        dayOfMonth: data.dayOfMonth != null ? Number(data.dayOfMonth) : null,
        transactionGroupId: data.transactionGroupId ?? null,
        transactionSubgroupId: data.transactionSubgroupId ?? null,
        isActive: data.isActive ?? true,
      },
    });

    // Wystąpienia są materializowane z wyprzedzeniem. Aktualizujemy ich
    // klasyfikację razem z szablonem, żeby zmiana była od razu widoczna
    // w już wygenerowanej projekcji.
    await this.prisma.transaction.updateMany({
      where: {
        recurringTemplateId: id,
        isGenerated: true,
        type: 'recurring',
      },
      data: {
        transactionGroupId: updated.transactionGroupId,
        transactionSubgroupId: updated.transactionSubgroupId,
      },
    });

    return updated;
  }

  async deleteRecurringTemplate(id: number) {
    const existing = await this.prisma.recurringTemplate.findUnique({
      where: { id },
    });
    if (!existing) {
      throw new NotFoundException(`Szablon ${id} nie istnieje.`);
    }

    await this.prisma.recurringTemplate.delete({ where: { id } });
  }

  async getProjectionDefaultRange() {
    const today = this.normalizeDate(this.toDateString(new Date()));
    const currentMonthStart = new Date(today.getFullYear(), today.getMonth(), 1);
    currentMonthStart.setHours(0, 0, 0, 0);

    const currentMonthEnd = this.getMonthEnd(today);
    currentMonthEnd.setHours(0, 0, 0, 0);

    const daysToCurrentMonthEnd = this.diffDays(today, currentMonthEnd);
    const defaultEnd =
      daysToCurrentMonthEnd < 10
        ? this.getMonthEnd(new Date(today.getFullYear(), today.getMonth() + 1, 1))
        : currentMonthEnd;

    const lastSalaryTx = await this.prisma.transaction.findFirst({
      where: { isSalaryIncome: true, income: { not: null } },
      orderBy: [{ date: 'desc' }, { id: 'desc' }],
    });

    const lastSalaryDate = lastSalaryTx
      ? this.normalizeDate(this.toDateString(lastSalaryTx.date))
      : null;

    const defaultStart =
      lastSalaryDate && lastSalaryDate < currentMonthStart
        ? lastSalaryDate
        : currentMonthStart;

    return {
      projectionStart: this.toDateString(defaultStart),
      projectionEnd: this.toDateString(defaultEnd),
      lastSalaryDate: lastSalaryDate ? this.toDateString(lastSalaryDate) : null,
    };
  }

  async generateProjection(startDateStr: string, endDateStr: string) {
    try {
      const startDate = this.normalizeDate(startDateStr);
      const endDate = this.normalizeDate(endDateStr);

      if (endDate < startDate) {
        throw new BadRequestException('Data końcowa nie może być wcześniejsza niż początkowa.');
      }

      const summaryEndDate = this.addMonths(startDate, 12);
	  
      const budgetSetting = await this.prisma.globalSettings.findFirst({
        where: { key: 'daily_budget' },
      });
      const dailyBudget = budgetSetting ? parseFloat(budgetSetting.value) : 130;

      const accounts = await this.prisma.account.findMany({
        include: {
          accountType: {
            select: {
              code: true,
            },
          },
        },
        orderBy: { id: 'asc' },
      });
	  
	  const creditCardType = await this.prisma.accountType.findFirst({
	    where: {
    	  OR: [{ code: 'credit_card' }, { code: 'credit_card' }],
  	  },
	  });

      await this.materializeRecurringTransactions(startDate, summaryEndDate, accounts);

      const includedAccountIds = new Set<number>(
        accounts
          .filter((account) => {
            if (!account.includeInDailyBudget) return false;

            const isAutoRepaidCreditCard =
              account.accountType?.code === 'credit_card' &&
              account.autoRepaymentEnabled &&
              account.repaymentAccountId != null;

            return !isAutoRepaidCreditCard;
          })
          .map((account) => account.id),
      );

      const accountNameMap: Record<number, string> = Object.fromEntries(
        accounts.map((account) => [account.id, account.name]),
      );

      const openingBalances: Record<number, number> = {};
      for (const account of accounts) {
        openingBalances[account.id] = Number(account.initialBalance);
      }

      const openingTransactions = await this.prisma.transaction.findMany({
        where: { date: { lt: startDate } },
        include: {
          transactionGroup: {
            select: { id: true, name: true },
          },
          transactionSubgroup: {
            select: { id: true, name: true },
          },
        },
        orderBy: [{ date: 'asc' }, { id: 'asc' }],
      });

      for (const tx of openingTransactions) {
        this.applyTransactionToBalances(tx, openingBalances);
      }

      const visibleTransactions = await this.prisma.transaction.findMany({
        where: {
          date: {
            gte: startDate,
            lte: endDate,
          },
        },
        include: {
          transactionGroup: {
            select: { id: true, name: true },
          },
          transactionSubgroup: {
            select: { id: true, name: true },
          },
        },
        orderBy: [{ date: 'asc' }, { id: 'asc' }],
      });

      const summaryTransactions = await this.prisma.transaction.findMany({
        where: {
          date: {
            gte: startDate,
            lte: summaryEndDate,
          },
        },
        include: {
          transactionGroup: {
            select: { id: true, name: true },
          },
          transactionSubgroup: {
            select: { id: true, name: true },
          },
        },
        orderBy: [{ date: 'asc' }, { id: 'asc' }],
      });

      const rowsByDate = new Map<string, ProjectionRow[]>();
      const balancesForRows = { ...openingBalances };
      let runningTotalBalance = this.sumBalances(balancesForRows);

      for (const tx of visibleTransactions) {
        const dateStr = this.toDateString(tx.date);
        const rows = this.buildRowsForTransaction(
          tx,
          balancesForRows,
          runningTotalBalance,
          accountNameMap,
        );

        if (!rowsByDate.has(dateStr)) {
          rowsByDate.set(dateStr, []);
        }
        rowsByDate.get(dateStr)!.push(...rows);

        this.applyTransactionToBalances(tx, balancesForRows);
        runningTotalBalance = this.sumBalances(balancesForRows);
      }

      const timeline: Array<{
        date: string;
        rows: ProjectionRow[];
        balances: Record<number, number>;
        totalBalance: number;
        dailyBudgetBalance: number;
      }> = [];

      const fullTimeline: Array<{
        date: string;
        balances: Record<number, number>;
        totalBalance: number;
        dailyBudgetBalance: number;
      }> = [];

      const visibleTransactionsByDate = new Map<string, any[]>();
      for (const tx of visibleTransactions) {
        const dateStr = this.toDateString(tx.date);
        if (!visibleTransactionsByDate.has(dateStr)) {
          visibleTransactionsByDate.set(dateStr, []);
        }
        visibleTransactionsByDate.get(dateStr)!.push(tx);
      }

      const summaryTransactionsByDate = new Map<string, any[]>();
      for (const tx of summaryTransactions) {
        const dateStr = this.toDateString(tx.date);
        if (!summaryTransactionsByDate.has(dateStr)) {
          summaryTransactionsByDate.set(dateStr, []);
        }
        summaryTransactionsByDate.get(dateStr)!.push(tx);
      }

      const rollingBalancesVisible = { ...openingBalances };
      const visibleCursor = new Date(startDate);

      while (visibleCursor <= endDate) {
        const dateStr = this.toDateString(visibleCursor);
        const dayTransactions = visibleTransactionsByDate.get(dateStr) ?? [];

        for (const tx of dayTransactions) {
          this.applyTransactionToBalances(tx, rollingBalancesVisible);
        }

        const balancesSnapshot = { ...rollingBalancesVisible };
        const totalBalance = this.sumBalances(balancesSnapshot);
        const dailyBudgetBalance = this.sumIncludedBalances(balancesSnapshot, includedAccountIds);

        timeline.push({
          date: dateStr,
          rows: rowsByDate.get(dateStr) ?? [],
          balances: balancesSnapshot,
          totalBalance,
          dailyBudgetBalance,
        });

        visibleCursor.setDate(visibleCursor.getDate() + 1);
      }

      const rollingBalancesFull = { ...openingBalances };
      const summaryCursor = new Date(startDate);

      while (summaryCursor <= summaryEndDate) {
        const dateStr = this.toDateString(summaryCursor);
        const dayTransactions = summaryTransactionsByDate.get(dateStr) ?? [];

        for (const tx of dayTransactions) {
          this.applyTransactionToBalances(tx, rollingBalancesFull);
        }

        const balancesSnapshot = { ...rollingBalancesFull };
        const totalBalance = this.sumBalances(balancesSnapshot);
        const dailyBudgetBalance = this.sumIncludedBalances(balancesSnapshot, includedAccountIds);

        fullTimeline.push({
          date: dateStr,
          balances: balancesSnapshot,
          totalBalance,
          dailyBudgetBalance,
        });

        summaryCursor.setDate(summaryCursor.getDate() + 1);
      }

      const today = this.normalizeDate(this.toDateString(new Date()));
      const projectionAnchorDate = startDate > today ? startDate : today;
      const anchorDateStr = this.toDateString(projectionAnchorDate);

      const manualNextSalaryDateSetting = await this.prisma.globalSettings.findFirst({
        where: { key: 'manual_next_salary_date' },
      });

      const manualNextSalaryDate = manualNextSalaryDateSetting?.value
        ? this.toDateString(this.normalizeDate(manualNextSalaryDateSetting.value))
        : null;

      const lastSalaryTx = [...summaryTransactions]
        .filter(
          (tx) =>
            !!tx.isSalaryIncome &&
            Number(tx.income ?? 0) > 0 &&
            !!tx.accountId &&
            includedAccountIds.has(tx.accountId),
        )
        .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())[0];

      const computedNextSalaryDate =
        lastSalaryTx ? this.computeNextSalaryDateFromLastSalary(this.normalizeDate(this.toDateString(lastSalaryTx.date))) : null;

      const nextSalaryDate = manualNextSalaryDate || computedNextSalaryDate;

      const anchorDay =
        fullTimeline.find((day) => day.date === anchorDateStr) ||
        fullTimeline.find((day) => day.date > anchorDateStr) ||
        fullTimeline[fullTimeline.length - 1];

      const salaryDay =
        (nextSalaryDate &&
          (fullTimeline.find((day) => day.date === nextSalaryDate) ||
            fullTimeline.find((day) => day.date > nextSalaryDate))) ||
        null;

      const summaryDay = salaryDay || anchorDay;

      const totalBalanceAtSalary = summaryDay?.totalBalance ?? 0;
      const dailyBudgetBalanceAtSalary = summaryDay?.dailyBudgetBalance ?? 0;

      const budgetHorizonDate = nextSalaryDate ? this.normalizeDate(nextSalaryDate) : endDate;
      const daysToSalary = this.diffDays(projectionAnchorDate, budgetHorizonDate);

      const availableDailyBudget =
        daysToSalary > 0 ? dailyBudgetBalanceAtSalary / daysToSalary : dailyBudgetBalanceAtSalary;

      const variance = dailyBudgetBalanceAtSalary - daysToSalary * dailyBudget;

      return {
        timeline,
        summary: {
          projectionStart: this.toDateString(startDate),
          projectionEnd: this.toDateString(endDate),
          nextSalaryDate,
          daysToSalary,
          totalBalance: totalBalanceAtSalary,
          dailyBudgetBalance: dailyBudgetBalanceAtSalary,
          dailyBudget,
          availableDailyBudget,
          variance,
        },
      };
    } catch (error: any) {
      console.error('CRITICAL ERROR in generateProjection', error);

      if (error instanceof BadRequestException) {
        throw error;
      }

      throw new InternalServerErrorException(error?.message || 'Błąd obliczeń projekcji.');
    }
  }

  private validateRecurringTemplateInput(data: {
    accountId: number;
    info: string;
    amount: number;
    startDate: string;
    endDate?: string;
    multiplier?: number;
    period: string;
    dayOfMonth?: number;
    transactionGroupId?: number | null;
    transactionSubgroupId?: number | null;
  }) {
    if (!data.accountId) {
      throw new BadRequestException('Szablon cykliczny wymaga konta.');
    }
    if (!data.info?.trim()) {
      throw new BadRequestException('Opis szablonu jest wymagany.');
    }
    if (!data.startDate) {
      throw new BadRequestException('Data startowa jest wymagana.');
    }
    if (!data.amount || Number(data.amount) <= 0) {
      throw new BadRequestException('Kwota szablonu musi być dodatnia.');
    }
    if (!['day', 'month', 'year'].includes(data.period)) {
      throw new BadRequestException('Niepoprawny okres szablonu.');
    }
    if (data.multiplier && Number(data.multiplier) <= 0) {
      throw new BadRequestException('Mnożnik częstotliwości musi być dodatni.');
    }
    if (data.period === 'month' && data.dayOfMonth != null) {
      const day = Number(data.dayOfMonth);
      if (day < 1 || day > 31) {
        throw new BadRequestException('dayOfMonth musi mieścić się w zakresie 1-31.');
      }
    }
  }

  private async materializeRecurringTransactions(startDate: Date, endDate: Date, accounts: any[]) {
    const templates = await this.prisma.recurringTemplate.findMany({
      where: {
        isActive: true,
        startDate: { lte: endDate },
        OR: [{ endDate: null }, { endDate: { gte: startDate } }],
      },
      orderBy: { id: 'asc' },
    });

    for (const template of templates) {
      const occurrences = this.getOccurrenceDates(template, startDate, endDate);

      for (const occurrence of occurrences) {
        const existing = await this.prisma.transaction.findFirst({
          where: {
            recurringTemplateId: template.id,
            recurrenceDate: occurrence,
          },
        });

        if (existing) continue;

        await this.prisma.transaction.create({
          data: {
            userId: 0,
            date: occurrence,
            info: template.info,
            income: null,
            expense: Number(template.amount),
            type: 'recurring',
            isCleared: false,
            isSalaryIncome: false,
            accountId: template.accountId,
            sourceAccountId: null,
            destinationAccountId: null,
            transactionGroupId: template.transactionGroupId,
            transactionSubgroupId: template.transactionSubgroupId,
            recurringTemplateId: template.id,
            recurrenceDate: occurrence,
            isGenerated: true,
          },
        });
      }
    }
	
    const creditCardType = await this.prisma.accountType.findFirst({
      where: {
        OR: [{ code: 'credit_card' }, { code: 'credit_card' }],
      },
    });

    if (!creditCardType) {
      return;
    }

    const defaultRepaymentGroup = await this.prisma.transactionGroup.findFirst({
      where: { code: 'system' },
    });

    const defaultRepaymentSubgroup = await this.prisma.transactionSubgroup.findFirst({
      where: { code: 'credit-card-repayment' },
    });

    const creditCards = accounts.filter(
      (account) =>
        account.accountTypeId === creditCardType.id &&
        account.autoRepaymentEnabled &&
        account.repaymentAccountId != null,
    );
    const today = this.normalizeDate(this.toDateString(new Date()));

    for (const creditCard of creditCards) {
      const repaymentDates = this.getAutoRepaymentDates(
        creditCard.autoRepaymentOffsetDays ?? 1,
        startDate,
        endDate,
      );

      for (const repaymentDate of repaymentDates) {
        // Historia nie jest projekcją: rzeczywistych, minionych spłat nie
        // wolno zmieniać ani usuwać po ponownym przeliczeniu salda karty.
        if (repaymentDate < today) continue;

        const closingDate = new Date(repaymentDate);
        // Spłata obejmuje wszystkie operacje wykonane do dnia poprzedzającego
        // termin spłaty. Wcześniej odejmowaliśmy tutaj cały offset, przez co
        // np. spłata 19. dnia miesiąca uwzględniała tylko operacje do 1. dnia.
        closingDate.setDate(closingDate.getDate() - 1);
        closingDate.setHours(0, 0, 0, 0);

        const generationKey = `auto-repayment:${creditCard.id}:${this.toDateString(repaymentDate)}`;
        const repaymentGroupId =
          creditCard.autoRepaymentGroupId ?? defaultRepaymentGroup?.id ?? null;
        const repaymentSubgroupId =
          creditCard.autoRepaymentSubgroupId ?? defaultRepaymentSubgroup?.id ?? null;

        const existing = await this.prisma.transaction.findUnique({
          where: { generationKey },
        });

        // Ręcznie rozliczona spłata jest potwierdzona i również nie powinna
        // zostać nadpisana przez automatykę, nawet gdy jej termin jest dziś
        // lub w przyszłości.
        if (existing?.isCleared) continue;

        const cardTransactions = await this.prisma.transaction.findMany({
          where: {
            date: { lte: closingDate },
            OR: [
              { accountId: creditCard.id },
              { sourceAccountId: creditCard.id },
              { destinationAccountId: creditCard.id },
            ],
          },
          orderBy: [{ date: 'asc' }, { id: 'asc' }],
        });

        let cardBalance = Number(creditCard.initialBalance ?? 0);
        for (const tx of cardTransactions.filter((tx) => tx.generationKey !== generationKey)) {
          if (tx.type === 'transfer') {
            if (tx.sourceAccountId === creditCard.id) {
              cardBalance -= Number(tx.expense ?? 0);
            }
            if (tx.destinationAccountId === creditCard.id) {
              cardBalance += Number(tx.expense ?? 0);
            }
          } else if (tx.accountId === creditCard.id) {
            cardBalance += Number(tx.income ?? 0) - Number(tx.expense ?? 0);
          }
        }

        const repaymentAmount = Math.max(0, -cardBalance);

        if (existing) {
          if (repaymentAmount <= 0) {
            // Zwrot lub korekta mogła zmniejszyć zadłużenie do zera.
            // Usuń wtedy wcześniej wygenerowaną, już niepotrzebną spłatę.
            await this.prisma.transaction.delete({ where: { id: existing.id } });
          } else if (
            Number(existing.expense ?? 0) !== repaymentAmount ||
            existing.transactionGroupId !== repaymentGroupId ||
            existing.transactionSubgroupId !== repaymentSubgroupId
          ) {
            await this.prisma.transaction.update({
              where: { id: existing.id },
              data: {
                expense: repaymentAmount,
                transactionGroupId: repaymentGroupId,
                transactionSubgroupId: repaymentSubgroupId,
              },
            });
          }
          continue;
        }

        if (repaymentAmount <= 0) continue;

        await this.prisma.transaction.create({
          data: {
            userId: 0,
            date: repaymentDate,
            info: `Automatyczna spłata: ${creditCard.name}`,
            income: null,
            expense: repaymentAmount,
            type: 'transfer',
            isCleared: false,
            isSalaryIncome: false,
            transactionGroupId: repaymentGroupId,
            transactionSubgroupId: repaymentSubgroupId,
            accountId: null,
            sourceAccountId: creditCard.repaymentAccountId,
            destinationAccountId: creditCard.id,
            recurringTemplateId: null,
            recurrenceDate: null,
            isGenerated: true,
            generationKey,
            generationKind: 'auto_repayment',
            autoGeneratedSourceAccountId: creditCard.id,
          },
        });
      }
    }
  }

  private getOccurrenceDates(template: any, from: Date, to: Date): Date[] {
    const dates: Date[] = [];
    const current = new Date(template.startDate);
    current.setHours(0, 0, 0, 0);

    const end = template.endDate ? new Date(template.endDate) : null;
    if (end) end.setHours(0, 0, 0, 0);

    while (current <= to) {
      if (
        current >= from &&
        (!end || current <= end) &&
        this.isRecurringTriggerDay(current, template)
      ) {
        dates.push(new Date(current));
      }

      current.setDate(current.getDate() + 1);

      if (dates.length > 2000) break;
    }

    return dates;
  }
  
  private getAutoRepaymentDates(offsetDays: number, from: Date, to: Date): Date[] {
  const dates: Date[] = [];
  const cursor = new Date(from.getFullYear(), from.getMonth(), 1);
  cursor.setHours(0, 0, 0, 0);

  while (cursor <= to) {
    const monthStart = new Date(cursor.getFullYear(), cursor.getMonth(), 1);
    const repaymentDate = new Date(monthStart);
    repaymentDate.setDate(repaymentDate.getDate() + Number(offsetDays || 0));
    repaymentDate.setHours(0, 0, 0, 0);
	
    if (repaymentDate >= from && repaymentDate <= to) {
      dates.push(new Date(repaymentDate));
    }
	
    cursor.setMonth(cursor.getMonth() + 1);
  }

    return dates;
  }
  

  private buildRowsForTransaction(
    tx: TransactionWithCategory,
    balancesBefore: Record<number, number>,
    totalBalanceBefore: number,
    accountNameMap: Record<number, string>,
  ): ProjectionRow[] {
    const income = Number(tx.income ?? 0);
    const expense = Number(tx.expense ?? 0);

    if (tx.type === 'transfer') {
      const amount = expense;
      const sourceBefore = balancesBefore[tx.sourceAccountId] ?? 0;
      const destinationBefore = balancesBefore[tx.destinationAccountId] ?? 0;
      const sourceAfter = sourceBefore - amount;
      const destinationAfter = destinationBefore + amount;

      return [
        {
          rowId: `${tx.id}-out`,
          transactionId: tx.id,
          date: this.toDateString(tx.date),
          info: `${tx.info} przelew wychodzący`,
          type: tx.type,
          isCleared: tx.isCleared,
          isSalaryIncome: false,
          accountId: tx.sourceAccountId,
          accountName: accountNameMap[tx.sourceAccountId] ?? '',
          income: 0,
          expense: amount,
          accountBalanceAfter: sourceAfter,
          totalBalanceAfter: totalBalanceBefore,
          isRecurringGenerated: !!tx.isGenerated,
          isAutoGenerated: !!tx.autoGeneratedSourceAccountId,
          generationKind: tx.generationKind ?? null,
          transactionGroupId: tx.transactionGroupId ?? null,
          transactionGroupName: tx.transactionGroup?.name ?? null,
          transactionSubgroupId: tx.transactionSubgroupId ?? null,
          transactionSubgroupName: tx.transactionSubgroup?.name ?? null,
          recurringTemplateId: tx.recurringTemplateId ?? null,
          transferSide: 'out',
        },
        {
          rowId: `${tx.id}-in`,
          transactionId: tx.id,
          date: this.toDateString(tx.date),
          info: `${tx.info} przelew przychodzący`,
          type: tx.type,
          isCleared: tx.isCleared,
          isSalaryIncome: false,
          accountId: tx.destinationAccountId,
          accountName: accountNameMap[tx.destinationAccountId] ?? '',
          income: amount,
          expense: 0,
          accountBalanceAfter: destinationAfter,
          totalBalanceAfter: totalBalanceBefore,
          isRecurringGenerated: !!tx.isGenerated,
          isAutoGenerated: !!tx.autoGeneratedSourceAccountId,
          generationKind: tx.generationKind ?? null,
          transactionGroupId: tx.transactionGroupId ?? null,
          transactionGroupName: tx.transactionGroup?.name ?? null,
          transactionSubgroupId: tx.transactionSubgroupId ?? null,
          transactionSubgroupName: tx.transactionSubgroup?.name ?? null,
          recurringTemplateId: tx.recurringTemplateId ?? null,
          transferSide: 'in',
        },
      ];
    }

    const accountId = tx.accountId;
    const before = accountId ? (balancesBefore[accountId] ?? 0) : 0;
    const after = before + income - expense;
    const totalAfter = totalBalanceBefore + income - expense;

    return [
      {
        rowId: String(tx.id),
        transactionId: tx.id,
        date: this.toDateString(tx.date),
        info: tx.info,
        type: tx.type,
        isCleared: tx.isCleared,
        isSalaryIncome: !!tx.isSalaryIncome,
        accountId,
        accountName: accountId ? (accountNameMap[accountId] ?? '') : '',
        income,
        expense,
        accountBalanceAfter: accountId ? after : null,
        totalBalanceAfter: totalAfter,
        isRecurringGenerated: !!tx.isGenerated,
        isAutoGenerated: !!tx.autoGeneratedSourceAccountId,
        generationKind: tx.generationKind ?? null,
        transactionGroupId: tx.transactionGroupId ?? null,
        transactionGroupName: null,
        transactionSubgroupId: tx.transactionSubgroupId ?? null,
        transactionSubgroupName: null,
        recurringTemplateId: tx.recurringTemplateId ?? null,
        transferSide: null,
      },
    ];
  }

  private applyTransactionToBalances(tx: any, balances: Record<number, number>) {
    const income = Number(tx.income ?? 0);
    const expense = Number(tx.expense ?? 0);

    if (tx.type === 'transfer') {
      if (tx.sourceAccountId) {
        balances[tx.sourceAccountId] = (balances[tx.sourceAccountId] ?? 0) - expense;
      }
      if (tx.destinationAccountId) {
        balances[tx.destinationAccountId] = (balances[tx.destinationAccountId] ?? 0) + expense;
      }
      return;
    }

    if (tx.accountId) {
      balances[tx.accountId] = (balances[tx.accountId] ?? 0) + income - expense;
    }
  }

  private sumBalances(balances: Record<number, number>) {
    return Object.values(balances).reduce((acc, value) => acc + Number(value || 0), 0);
  }

  private sumIncludedBalances(balances: Record<number, number>, includedAccountIds: Set<number>) {
    return Object.entries(balances).reduce((sum, [accountId, balance]) => {
      return includedAccountIds.has(Number(accountId)) ? sum + Number(balance || 0) : sum;
    }, 0);
  }

  private normalizeDate(dateStr: string) {
    const date = new Date(`${dateStr}T00:00:00`);
    date.setHours(0, 0, 0, 0);
    return date;
  }

  private toDateString(date: Date) {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  }

  private diffDays(from: Date, to: Date) {
    const ms = to.getTime() - from.getTime();
    return Math.max(0, Math.round(ms / 86400000));
  }

  private addMonths(date: Date, months: number) {
    const result = new Date(date);
    result.setMonth(result.getMonth() + months);
    return result;
  }

  private isRecurringTriggerDay(currentDate: Date, template: any): boolean {
    const startDate = new Date(template.startDate);
    startDate.setHours(0, 0, 0, 0);

    const multiplier = template.multiplier || 1;
    const period = template.period;

    if (period === 'day') {
      const diffMs = currentDate.getTime() - startDate.getTime();
      const diffDays = Math.floor(diffMs / 86400000);
      return diffDays >= 0 && diffDays % multiplier === 0;
    }

    if (period === 'month') {
      const triggerDay = template.dayOfMonth ?? startDate.getDate();
      if (currentDate.getDate() !== triggerDay) return false;

      const monthsDiff =
        (currentDate.getFullYear() - startDate.getFullYear()) * 12 +
        (currentDate.getMonth() - startDate.getMonth());

      return monthsDiff >= 0 && monthsDiff % multiplier === 0;
    }

    if (period === 'year') {
      if (currentDate.getDate() !== startDate.getDate()) return false;
      if (currentDate.getMonth() !== startDate.getMonth()) return false;

      const yearsDiff = currentDate.getFullYear() - startDate.getFullYear();
      return yearsDiff >= 0 && yearsDiff % multiplier === 0;
    }

    return false;
  }
  
  private computeNextSalaryDateFromLastSalary(lastSalaryDate: Date): string {
    const monthEnd = this.getMonthEnd(lastSalaryDate);
    const daysToMonthEnd = this.diffDays(lastSalaryDate, monthEnd);

    const targetBaseDate =
      daysToMonthEnd <= 5
        ? new Date(lastSalaryDate.getFullYear(), lastSalaryDate.getMonth() + 1, 1)
        : new Date(lastSalaryDate.getFullYear(), lastSalaryDate.getMonth(), 1);

    const targetDate = this.getPenultimateBusinessDay(targetBaseDate);
    return this.toDateString(targetDate);
  }

  private getMonthEnd(date: Date): Date {
    return new Date(date.getFullYear(), date.getMonth() + 1, 0);
  }

  private getPenultimateBusinessDay(monthDate: Date): Date {
    const year = monthDate.getFullYear();
    const month = monthDate.getMonth();
    const lastDay = new Date(year, month + 1, 0);

    const businessDays: Date[] = [];
    for (let day = 1; day <= lastDay.getDate(); day++) {
      const current = new Date(year, month, day);
      const dow = current.getDay();
      if (dow !== 0 && dow !== 6) {
        businessDays.push(current);
      }
    }

    if (businessDays.length === 0) {
      return lastDay;
    }

    if (businessDays.length === 1) {
      return businessDays[0];
    }

    return businessDays[businessDays.length - 2];

  }
}
