export type ActiveTab = 'transaction' | 'analytics' | 'transfer' | 'recurring' | 'account' | 'category';
export type ViewMode = 'transactions' | 'analytics' | 'recurring' | 'accounts' | 'categories' | 'users';

export type AuthUser = {
  id: number;
  username: string;
  firstName?: string | null;
  lastName?: string | null;
  email?: string | null;
  role: 'USER' | 'ADMIN';
  isActive: boolean;
};
export type ManagedUserForm = { username: string; password: string; role: 'USER' | 'ADMIN'; isActive: boolean };

export type Account = {
  id: number;
  name: string;
  accountTypeId: number;
  accountType?: { id: number; code: string; name: string } | null;
  initialBalance: number;
  includeInDailyBudget: boolean;
  creditLimit?: number | null;
  repaymentAccountId?: number | null;
  autoRepaymentEnabled?: boolean;
  autoRepaymentOffsetDays?: number;
  autoRepaymentGroupId?: number | null;
  autoRepaymentSubgroupId?: number | null;
  autoRepaymentGroup?: { id: number; name: string } | null;
  autoRepaymentSubgroup?: { id: number; name: string } | null;
  repaymentAccount?: { id: number; name: string } | null;
};

export type TransactionSubgroup = {
  id: number;
  transactionGroupId: number;
  code: string;
  name: string;
  sortOrder: number;
  isSystem: boolean;
  isActive: boolean;
};

export type TransactionGroup = {
  id: number;
  code: string;
  name: string;
  sortOrder: number;
  isSystem: boolean;
  isActive: boolean;
  subgroups: TransactionSubgroup[];
};

export type CategoryFormMode = 'group' | 'subgroup';
export type CategoryFormState = { code: string; name: string; sortOrder: string; transactionGroupId: string };

export type TransactionListItem = {
  id: number;
  date: string;
  info: string;
  income: number;
  expense: number;
  incomeFormula?: string | null;
  expenseFormula?: string | null;
  type: string;
  isCleared: boolean;
  isSalaryIncome: boolean;
  accountId?: number | null;
  sourceAccountId?: number | null;
  destinationAccountId?: number | null;
  transactionGroupId?: number | null;
  transactionSubgroupId?: number | null;
  transactionGroupName?: string | null;
  transactionSubgroupName?: string | null;
};

export type ProjectionRow = {
  rowId: string;
  transactionId: number;
  date: string;
  info: string;
  type: string;
  isCleared: boolean;
  isSalaryIncome: boolean;
  accountId: number | null;
  accountName: string;
  income: number;
  expense: number;
  incomeFormula: string | null;
  expenseFormula: string | null;
  accountBalanceAfter: number | null;
  totalBalanceAfter: number;
  isRecurringGenerated: boolean;
  isAutoGenerated: boolean;
  generationKind: string | null;
  transactionGroupId: number | null;
  transactionGroupName: string | null;
  transactionSubgroupId: number | null;
  transactionSubgroupName: string | null;
  recurringTemplateId: number | null;
  transferSide: 'out' | 'in' | null;
};

export type ProjectionDay = {
  date: string;
  rows: ProjectionRow[];
  balances: Record<string, number>;
  totalBalance: number;
  dailyBudgetBalance: number;
};

export type ProjectionSummary = {
  projectionStart: string;
  projectionEnd: string;
  nextSalaryDate: string | null;
  daysToSalary: number;
  totalBalance: number;
  dailyBudgetBalance: number;
  dailyBudget: number;
  availableDailyBudget: number;
  variance: number;
};

export type ProjectionResponse = { timeline: ProjectionDay[]; summary: ProjectionSummary };
export type ProjectionDefaultRangeResponse = { projectionStart: string; projectionEnd: string; lastSalaryDate: string | null };

export type RecurringTemplate = {
  id: number;
  accountId: number;
  info: string;
  amount: number;
  startDate: string;
  endDate?: string | null;
  multiplier: number;
  period: 'day' | 'month' | 'year';
  dayOfMonth?: number | null;
  isActive?: boolean;
  account?: { name: string };
  transactionGroupId?: number | null;
  transactionSubgroupId?: number | null;
  transactionGroup?: { id: number; name: string } | null;
  transactionSubgroup?: { id: number; name: string } | null;
};

export type SettingsResponse = Record<string, string>;

export type ReceiptAnalysis = {
  merchant: { value: string | null; confidence: 'low' | 'medium' | 'high' | null; evidence: string | null };
  date: { value: string | null; confidence: 'low' | 'medium' | 'high' | null; evidence: string | null };
  total: { value: number | null; currency: 'PLN'; confidence: 'low' | 'medium' | 'high' | null; evidence: string | null };
  suggestion: {
    accountId: number | null;
    transactionGroupId: number | null;
    transactionSubgroupId: number | null;
  };
  warnings: string[];
};

export type FormDataState = {
  date: string;
  startDate: string;
  endDate: string;
  accountId: string;
  sourceAccountId: string;
  destinationAccountId: string;
  info: string;
  income: string;
  expense: string;
  amount: string;
  frequencyMultiplier: string;
  frequencyPeriod: 'day' | 'month' | 'year';
  dayOfMonth: string;
  accountName: string;
  accountTypeId: string;
  initialBalance: string;
  includeInDailyBudget: boolean;
  creditLimit: string;
  repaymentAccountId: string;
  autoRepaymentEnabled: boolean;
  autoRepaymentOffsetDays: string;
  autoRepaymentGroupId: string;
  autoRepaymentSubgroupId: string;
  isSalaryIncome: boolean;
  transactionGroupId: string;
  transactionSubgroupId: string;
};
